spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url:
      jdbc:oracle:thin:@db202202180852_high?TNS_ADMIN=C:/oracle/Wallet_DB202202180852
    username: admin
    password: Leaf950515!!