server:
  port: 8083
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url:
      jdbc:oracle:thin:@dboracle_high?TNS_ADMIN=C:/oracle/Wallet_Dboracle
    username: admin
    password: Dboracle9647!
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    path-match:
      matching-strategy: ant_path_matcher
app:
  jwtSecret: abcdefsfsdaofisdjofiasjdfiopsjofisdfsdafsdaasfsafsfsafsafd
  jwtExpirationMs: 864000
