spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url:
      jdbc:oracle:thin:@dboracle_high?TNS_ADMIN=C:/oracle/Wallet_Dboracle
    username: admin
    password: Dboracle9647!
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


